### ISSUE TITLE
Не выводится TV в редактировании ресурса

### ISSUE THREAD

**Issue by ghost** [mnoskov/commerce-options#4]
Evolution CMS 3.1.2
PHP 7.4.12

Все установилось хорошо, везде проставились события. Далее создал TV с типом commerce_options, заполнил возможные значения (в БД добавилось), привязал к Шаблону, но TV не выводится при редактировании ресурса для заполнения.
Ошибок нет нигде.

**Comment by mnoskov** [comment]
https://github.com/mnoskov/commerce-options/commit/47819cdb7241ee24d42bfe37caa8dfb0f4eb747c

**Comment by ghost** [comment]
Спасибо, работает.
